#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_newman="$(newman 2>/dev/null | awk '{print $NF}' | sed 's#^v###' || true)"
  jq -n --arg newman "$ver_newman" '{newman: $newman}'
}

version "$@"
